export interface UnidadeDeMedida {
    nome: string;
    símbolo: string;
}

export const UNIDADE_DE_MEDIDA = {
    api: { nome: 'API', símbolo: 'API' },
    atmosfera: { nome: 'Atmosfera', símbolo: 'atm' },
    centímetro: { nome: 'Centímetro', símbolo: 'cm' },
    darcy: { nome: 'Darcy', símbolo: 'D' },
    fator: { nome: 'Fator', símbolo: '- ' },
    gramasPorCentímetroCúbico: { nome: 'Grama por centímetro cúbico', símbolo: 'g/cm3' },
    gramasPorLitro: { nome: 'Grama por litro', símbolo: 'g/L' },
    gravidadeEspecífica: { nome: 'Gravidade específica', símbolo: 'sg' },
    grau: { nome: 'Grau', símbolo: 'deg' },
    quilogramaForça: { nome: 'Quilograma-força', símbolo: 'kgf' },
    quilogramasPorLitro: { nome: 'Quilograma por litro', símbolo: 'kg/L' },
    quilogramasPorMetroCúbico: { nome: 'Quilograma por metro cúbico', símbolo: 'kg/m3' },
    quilometroPorSegundo: { nome: 'Quilometro por segundo', símbolo: 'km/s' },
    quilopéPorSegundo: { nome: 'Quilope por segundo', símbolo: 'kft/s' },
    quiloLibra: { nome: 'Quilolibra', símbolo: 'klb' },
    quiloNewton: { nome: 'Quilonewton', símbolo: 'KN' },
    quilopascalPorMetro: { nome: 'Quilopascal por metro', símbolo: 'kPa/m' },
    libra: { nome: 'Libra', símbolo: 'lb' },
    libraPorBarril: { nome: 'Libra por barril', símbolo: 'lb/bbl' },
    libraPorPéCúbico: { nome: 'Libra por pé cúbico', símbolo: 'lb/ft3' },
    libraPorPolegadaQuadradaAbsoluta: { nome: 'Libra por polegada quadrada (absoluta)', símbolo: 'psi' },
    libraPorPolegadaQuadradaManométrica: { nome: 'Libra por polegada quadrada (manométrica)', símbolo: 'psig' },
    libraPorPolegadaQuadradaPorCemPés: { nome: 'Libra por polegada quadrada por cem pés', símbolo: 'psi/100ft' },
    librasPorGalão: { nome: 'Libra por galão', símbolo: 'lb/gal' },
    librasPorPolegadaQuadradaPorPé: { nome: 'Libra por polegada quadrada por pé', símbolo: 'psi/ft' },
    megaPascal: { nome: 'Megapascal', símbolo: 'MPa' },
    metro: { nome: 'Metro', símbolo: 'm' },
    metroPorHora: { nome: 'Metro por hora', símbolo: 'm/h' },
    metroPorMinuto: { nome: 'Metro por minuto', símbolo: 'm/min' },
    metroPorSegundo: { nome: 'Metro por segundo', símbolo: 'm/s' },
    microssegundoPorPé: { nome: 'Microsegundo por pé', símbolo: 'us/ft' },
    milidarcy: { nome: 'Milidarcy', símbolo: 'mD' },
    milímetro: { nome: 'Milímetro', símbolo: 'mm' },
    minutoPorMetro: { nome: 'Minuto por metro', símbolo: 'min/m' },
    newton: { nome: 'Newton', símbolo: 'N' },
    ohmPorMetro: { nome: 'Ohm por metro', símbolo: 'ohmn' },
    pé: { nome: 'Pé', símbolo: 'ft' },
    péPorHora: { nome: 'Pé por hora', símbolo: 'fph' },
    péPorMinuto: { nome: 'Pé por minuto', símbolo: 'fpm' },
    péPorSegundo: { nome: 'Pé por segundo', símbolo: 'fps' },
    polegada: { nome: 'Polegada', símbolo: 'in' },
    porcentagem: { nome: 'Porcentagem', símbolo: '%' },
    radiano: { nome: 'Radiano', símbolo: 'rad' },
    radianosPorSegundo: { nome: 'Radianos por segundo', símbolo: 'rad/s' },
    rotaçõesPorHora: { nome: 'Rotações por hora', símbolo: 'rph' },
    rotaçõesPorMinuto: { nome: 'Rotações por minuto', símbolo: 'rpm' },
    rotaçõesPorSegundo: { nome: 'Rotações por segundo', símbolo: 'rps' },
    segundoDeArco: { nome: 'Segundo de arco', símbolo: 'sec' },
    segundoPorMetro: { nome: 'Segundo por metro', símbolo: 's/m' },
    semDimensão: { nome: 'Sem dimensão', símbolo: '-' }, bar: { nome: 'Bar', símbolo: 'bar' },
    tonelada: { nome: 'Tonelada', símbolo: 't' },
};
