export const LITHO_TYPES = {
    'Projeto': ['Prevista', 'Adaptada'],
    'Monitoramento': ['Prevista', 'Interpretada'],
    'Retroanalise': ['Interpretada']
}

export const LITHO_GROUPS = [
    'Carbonatos',
    'Detríticas',
    'Arenitos',
    'Argilosas',
    'Ígneas',
    'Metamórficas',
    'Evaporitos',
    'Outros',
    'NãoIdentificado',
]

export const LITOLOGIA_CLASS = {
    'H2O': 'litho_0_h2o',
    'CAL': 'litho_01_cal',
    'CLC': 'litho_02_clc',
    'MRM': 'litho_03_mrm',
    'COQ': 'litho_04_coq',
    'MRD': 'litho_05_mrd',
    'CLU': 'litho_06_clu',
    'CSI': 'litho_07_csi',
    'CRE': 'litho_08_cre',
    'SID': 'litho_09_sid',
    'CRU': 'litho_10_cru',
    'CIM': 'litho_11_cim',
    'MDS': 'litho_12_mds',
    'WKS': 'litho_13_wks',
    'WAC': 'litho_13_wks', // Nomenclatura antiga
    'PKS': 'litho_14_pks',
    'PAC': 'litho_14_pks', // Nomenclatura antiga
    'GRS': 'litho_15_grs',
    'BLT': 'litho_16_blt',
    'BAF': 'litho_17_baf',
    'PHO': 'litho_18_pho',
    'CHT': 'litho_19_cht',
    'AGN': 'litho_20_agn',
    'AGL': 'litho_21_agl',
    'AGC': 'litho_22_agc',
    'AGS': 'litho_23_ags',
    'AGB': 'litho_24_agb',
    'ARL': 'litho_25_arl',
    'ARC': 'litho_26_arc',
    'ARO': 'litho_27_aro',
    'ARF': 'litho_28_arf',
    'ART': 'litho_29_art',
    'DOL': 'litho_30_dol',
    'RDS': 'litho_31_rds',
    'OCG': 'litho_32_ocg',
    'PNI': 'litho_33_pni',
    'VNI': 'litho_34_vni',
    'GBR': 'litho_35_gbr',
    'HIC': 'litho_36_hic',
    'MAF': 'litho_37_maf',
    'ULT': 'litho_38_ult',
    'BRR': 'litho_39_brr',
    'BRC': 'litho_40_brc',
    'BRV': 'litho_41_brv',
    'CGL': 'litho_42_cgl',
    'TON': 'litho_43_ton',
    'DMT': 'litho_44_dmt',
    'TOL': 'litho_45_tol',
    'TIL': 'litho_46_til',
    'TLT': 'litho_46_til', // Nomenclatura antiga 
    'TOS': 'litho_47_tos',
    'ARE': 'litho_48_are',
    'ARN': 'litho_49_arn',
    'ARB': 'litho_50_arb',
    'BDL': 'litho_51_bdl',
    'FLS': 'litho_52_fls',
    'LMA': 'litho_53_lma',
    'SLT': 'litho_54_slt',
    'ARG': 'litho_55_arg',
    'AGT': 'litho_56_agt',
    'FLH': 'litho_57_flh',
    'MRG': 'litho_58_mrg',
    'TOB': 'litho_59_tob',
    'VCL': 'litho_60_vcl',
    'TFU': 'litho_61_tfu',
    'CZV': 'litho_62_czv',
    'IGB': 'litho_63_igb',
    'INI': 'litho_64_ini',
    'DIA': 'litho_65_dia',
    'BAS': 'litho_66_bas',
    'GRN': 'litho_67_grn',
    'RLT': 'litho_68_rlt',
    'BDA': 'litho_69_bda',
    'MNI': 'litho_70_mni',
    'GNA': 'litho_71_gna',
    'FLT': 'litho_72_flt',
    'XST': 'litho_73_xst',
    'QZT': 'litho_74_qzt',
    'MAR': 'litho_75_mar',
    'MSI': 'litho_76_msi',
    'MST': 'litho_76_msi', // Nomenclatura antiga 
    'ARS': 'litho_77_ars',
    'ULB': 'litho_78_ulb',
    'ULS': 'litho_78_ulb', // Nomenclatura antiga 
    'MSD': 'litho_79_msd',
    'BOU': 'litho_80_bou',
    'TQD': 'litho_81_tqd',
    'AND': 'litho_82_and',
    'GIP': 'litho_83_gip',
    'SNI': 'litho_84_sni',
    'HAL': 'litho_85_hal',
    'SLV': 'litho_86_slv',
    'CRN': 'litho_87_crn',
    'FLO': 'litho_88_flo',
    'FRA': 'litho_89_fra',
    'LNT': 'litho_90_lnt',
    'TES': 'litho_91_tes',
    'CRV': 'litho_92_crv',
    'BIN': 'litho_93_bin',
    'SLX': 'litho_94_slx',
    'FNG': 'litho_95_fng',
    'LPL': 'litho_100_lpl',
    'AGV': 'litho_101_agv',
    'GRD': 'litho_102_grd',
    'DIO': 'litho_103_dio',
    'DCT': 'litho_104_dct',
    'TQT': 'litho_105_tqt',
    'ADT': 'litho_106_adt',
    'FNT': 'litho_107_fnt',
    'SNT': 'litho_108_snt',
    'ETR': 'litho_109_etr',
    'EBT': 'litho_110_ebt',
    'EAR': 'litho_111_ear',
    'EDD': 'litho_112_edd',
    'TRO': 'litho_113_tro',
    'DEN': 'litho_114_den',
    'LEI': 'litho_115_lei',
    'ESF': 'litho_116_esf',
    'TRV': 'litho_117_trv',
    'LMT': 'litho_118_lmt',
    'LML': 'litho_119_lml',
    'LMC': 'litho_120_lmc',
    'BAC': 'litho_121_bac',
    'LAT': 'litho_122_lat',
    'OUT': 'litho_-1_out',
    'AND_TQD_CRN': 'litho_82_and',
    'HAL_IGN': 'litho_85_hal',
    'N_IDENT': 'litho_-1_out'
}